### PR TITLE
fix: Change folder structure and add babel resolver

### PR DESCRIPTION
**Pull request by majidux**
Folders structure are now more cleaner.
Babel resolver helps more efficient and cleaner components import .

### CODE REVIEW

**Comment by m-esm** [comment]
Hi @majidux, Thanks for the PR. I'll review the changes and will merge them.

**Comment by majidux** [comment]
> Hi @majidux, Thanks for the PR. I'll review the changes and will merge them.

I think there is a problem with deployment on vercel, it should deploy the project after the merge was done not before.

**Comment by m-esm** [comment]
@majidux It's actually deploying the PR branch for us to do reviews and visual checks.

**Comment by majidux** [comment]
> @majidux It's actually deploying the PR branch for us to do reviews and visual checks.

Oh ok ,

**Comment by m-esm** [comment]
@majidux I'll add more commit to it on `stg` branch, then merge it with `main`

**Pull request merged**
